export const DUMMY_ANIME = [
  {
    id: 1,
    title: "ソードアート・オンライン Alternative",
    titleEn: "Sword Art Online Alternative",
    image: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/nx11757-Q563UzrlLnCx.jpg",
    genre: ["アクション", "ファンタジー"],
    genreColor: "bg-purple-600",
    episodes: 24,
    score: 8.0,
    description: "仮想世界を舞台にした壮大なバトルアクション。新たな冒険が始まる。",
    streaming: ["Netflix", "Amazon"],
    season: "2026春",
  },
  {
    id: 2,
    title: "魔法使いの約束 -Season 2-",
    titleEn: "Mahoutsukai no Yakusoku S2",
    image: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx101922-PEn1CTc93blC.jpg",
    genre: ["ファンタジー", "ドラマ"],
    genreColor: "bg-teal-500",
    episodes: 12,
    score: 7.8,
    description: "魔法使いたちが織りなす感動のストーリー。絆が試される第2シーズン。",
    streaming: ["Amazon"],
    season: "2026春",
  },
  {
    id: 3,
    title: "日常のぜんぶ",
    titleEn: "Nichijou no Zenbu",
    image: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx10165-KoMEPMCD9BRm.jpg",
    genre: ["コメディ", "日常"],
    genreColor: "bg-amber-500",
    episodes: 13,
    score: 8.2,
    description: "笑いが止まらない学園コメディ。個性豊かなキャラクターたちの日常。",
    streaming: ["Netflix"],
    season: "2026春",
  },
  {
    id: 4,
    title: "星降る夜のアリア",
    titleEn: "Hoshifuru Yoru no Aria",
    image: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx99426-bYGSNOKCTn2x.jpg",
    genre: ["恋愛", "ドラマ"],
    genreColor: "bg-pink-500",
    episodes: 12,
    score: 7.9,
    description: "音楽と恋が交差する青春ラブストーリー。切なくも美しい旋律。",
    streaming: ["Netflix", "Amazon"],
    season: "2026春",
  },
  {
    id: 5,
    title: "深淵のコード",
    titleEn: "Shin'en no Code",
    image: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx100120-HLbXWM1bGfMN.jpg",
    genre: ["SF", "ミステリー"],
    genreColor: "bg-blue-600",
    episodes: 24,
    score: 8.1,
    description: "AIが支配する近未来。一人のエンジニアが真実に挑むSFスリラー。",
    streaming: ["Amazon"],
    season: "2026春",
  },
  {
    id: 6,
    title: "僕のヒーローアカデミア",
    titleEn: "My Hero Academia",
    image: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx61374-7657cjgQ5GJA.jpg",
    genre: ["アクション", "ファンタジー"],
    genreColor: "bg-purple-600",
    episodes: 113,
    score: 8.4,
    description: "個性を持つ者が当たり前の世界で、無個性の少年がヒーローを目指す。",
    streaming: ["Netflix", "Amazon"],
    season: "2026春",
  },
  {
    id: 7,
    title: "Re:ゼロから始める異世界生活",
    titleEn: "Re:ZERO",
    image: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx79120-qMXGmSegVRMN.jpg",
    genre: ["ファンタジー", "ドラマ"],
    genreColor: "bg-teal-500",
    episodes: 25,
    score: 8.6,
    description: "異世界に召喚された青年が「死に戻り」の能力で困難に立ち向かう。",
    streaming: ["Amazon"],
    season: "2026春",
  },
  {
    id: 8,
    title: "ヴァイオレット・エヴァーガーデン",
    titleEn: "Violet Evergarden",
    image: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21827-10F6m50H4GJK.jpg",
    genre: ["ドラマ", "ファンタジー"],
    genreColor: "bg-gray-600",
    episodes: 13,
    score: 8.9,
    description: "「愛してる」の意味を知りたい元兵士の少女が手紙を届ける物語。",
    streaming: ["Netflix"],
    season: "2026春",
  },
  {
    id: 9,
    title: "呪術廻戦",
    titleEn: "Jujutsu Kaisen",
    image: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx113415-bbBWj4pEFseh.jpg",
    genre: ["アクション", "ホラー"],
    genreColor: "bg-purple-600",
    episodes: 24,
    score: 8.7,
    description: "呪霊と戦う呪術師たちの壮絶なバトルと人間ドラマ。",
    streaming: ["Netflix", "Amazon"],
    season: "2026春",
  },
  {
    id: 10,
    title: "薬屋のひとりごと",
    titleEn: "The Apothecary Diaries",
    image: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx161645-K3sBjOoHYoGE.jpg",
    genre: ["ミステリー", "ドラマ"],
    genreColor: "bg-purple-700",
    episodes: 24,
    score: 8.5,
    description: "後宮で働く薬師の少女が毒と謎を解き明かすミステリー。",
    streaming: ["Netflix", "Amazon"],
    season: "2026春",
  },
] as const;

export const TELOP_TITLES = DUMMY_ANIME.map((a) => a.title);
